<?php echo $this->broker('doctype')->direct() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
	<?php

	$this->broker('headLink')->direct()->appendStylesheet('/themes/default/css/admin.css');

	echo $this->broker('headTitle')->direct('Zly Default Frontend') . PHP_EOL .
		 $this->broker('headMeta')->direct() . PHP_EOL .
		 $this->broker('headLink')->direct() . PHP_EOL .
		 $this->broker('headStyle')->direct() . PHP_EOL .
		 //$this->dojo() . PHP_EOL .
		 $this->broker('headScript')->direct();
	?>
    <body class="claro">
        <div class="header">
            <div id="header">
                <div class="container">
                    <div id="logo">
                        <a href="<?php echo $this->broker('url')->direct(array('module' => '', 'action'=>''), 'admin', true); ?>">
                            Administrator Panel
                        </a>
                    </div>
                </div>
                <div class="user-menu"><?php echo $this->broker('layout')->getLayout()->usermenu; ?></div>
            </div>
            <div class="clear"></div>
        </div>
        <?php if (!empty($this->broker('layout')->getLayout()->left)) { ?>
            <div class="left">
                <div id="left"><?php echo $this->broker('layout')->getLayout()->left; ?></div>
            </div>
        <?php } ?>
        <div class="main-wrapper <?php if (!empty($this->broker('layout')->getLayout()->left))
            echo 'with-left'; ?>">

            <div class="subwrapper">
                <div class="breadcrumbs"><div class="main-breadcrumbs"><div class="left-breadcrumbs">
                            <div class="right-breadcrumbs">
                                <div class="breadcrumbs-link"><a class="breadcrumbs-home" href="/">&nbsp;</a></div>
                                <div class="breadcrumbs-separator"></div>
                                    <?php 
                                    echo $this->broker('navigation')
                                            ->breadcrumbs()
                                            ->setMinDepth(0)
                                            ->setLinkLast(true)
                                            ->setSeparator('<div class="breadcrumbs-separator"></div>'); 
                                    ?>
                            </div>
                        </div></div></div>


                <div class="main-content">
                    <?php echo $this->broker('layout')->getLayout()->top; ?>
                    <?php echo $this->broker('layout')->getLayout()->content; ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div id="footer">&copy; 2011 Zendmania. Powered by <a href="/zly">Zly Platform</a>
            <?php echo $this->broker('layout')->getLayout()->footer; ?></div>
        </div>
    </body>
</html>