<?php echo $this->broker('doctype')->direct() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Zendmania.com</title>
<link rel="stylesheet" href="/themes/zendmania/css/style.css" type="text/css"  />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<a class="logo" href="/"><img src="/themes/zendmania/images/logo.png" /></a>
			<div class="languages">
				<a class="en" href="#"></a>
				<a class="ru" href="#"></a>
			</div>
			<div class="clear-both"></div>
		</div>
		<div class="main">
			<div class="menu">
				<a href="#">Home</a>
				<a href="#">Projects</a>
				<a href="#">Downloads</a>
				<a href="#">Portfolio</a>
				<a href="#">About Us</a>
			</div>
                   
			<div class="content"> 
                            <!-- 	
				<div class="breadcrumbs">-> <a href="#">Projects</a> -> SlyS Platform</div>
				<div class="slider">
					<div class="title">SlyS Platform</div>
					<div class="subtitle">Free & Easy Zend Application Starting</div>
					<div class="description">
						There's never been easy to create and expand the application based on Zend Framework 1.8 +. 
						We offer our project SlyS Platform, distributed under Open Source, 
						which enables you to breathe easier programmer in the design and implementation 
						of various kinds and scope of web applications.
					</div>
					<a class="more" href="#">Learn more ...</a>
					<div class="clear-both"></div>
					<div class="switcher">
						<div class="switchers">1</div>
						<div class="switchers">2</div>
					</div>
					<div class="clear-both"></div>					
				</div>
				<div class="content-wrapper">
					<h3>Welcome to our website.</h3>
    The command of developers ZendMania is engaged in designing and an application creation based on Zend Framework.
     On the basis of our experience we have created some projects which purpose is to facilitate work as programmers Zend Framework (SlyS Platform)
	 and customers exacting to quality and expansibility of applications of sale of the goods (MarketPlace) and administrations of websites (SlyS CMS).
     We will be very glad if you use our projects and take part to working out on the terms of Open Source.
         
				</div>-->
            <?php echo $this->broker('layout')->getLayout()->content; ?>
			</div>
			<div class="clear-both"></div>
		</div>
		<div class="footer">
                    <div>
                        &copy; Zendmania 2009-2011. Powered by <a class="footer-link" href="/slys2">Slys Platform 2</a>
                    </div>
                    <div style="text-align: center;">
                        <!--VlexoFree_LinkBack-->
                    </div>
		</div>
	</div>
</body>
</html>
