<table class="admin-table">
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Actions</th>
    </tr>

    <?php
    if ($this->extendsListPaginator->count() > 0) {
        foreach ($this->extendsListPaginator as $item) {
    ?>

    <tr>
        <td><?php echo $item->id; ?></td>
        <td><?php echo $item->title; ?></td>
        <td>
            <?php
            echo $this->link(
				'edit',
				$this->url(array('action' => 'edit-extend', 'module' => 'sysmap', 'id' => $item->id)),
				array('class' => 'edit-item')
			);

            echo '&nbsp;/&nbsp;';

            echo $this->link(
				'delete',
				$this->url(array('action' => 'delete-extend', 'module' => 'sysmap', 'id' => $item->id)),
				array('class' => 'delete-item'),
                'are_you_sure'
			);
            ?>
        </td>
    </tr>

    <?php
        }
    }
    ?>
</table>

<?php echo $this->paginationControl($this->extendsListPaginator, 'Sliding', 'pagination_control.phtml'); ?>