<div>
    <a href="<?php echo $this->broker('url')->direct(array('action'=>'clean-cache'));?>">
                Clean sysmap cache
            </a>    
</div>
<div>
    <a href="<?php echo $this->broker('url')->direct(array('action'=>'clean-extensions-cache'));?>">
                Clean extensions cache
            </a>    
</div>
<table class="sysmap-list">
    <tr>
        <th>
            Module
        </th>
        <th>
            Controller
        </th>
        <th>
            Action
        </th>
        <th>
            Extensions
        </th>
    </tr>
    
<?php foreach($this->sysmapTree as $module) {?>
    <tr>
        <td>
            <div title="Hash: <?php echo $module->hash; ?>"><?php echo $module->name ?></div>
        </td>
        <td>
           
        </td>
        <td>
            
        </td>
        <td>
            
        </td>
    </tr>
    <?php foreach($module->_childrens as $controller) {?>
    <tr>
        <td>
            
        </td>
        <td>
            <div title="Hash: <?php echo $controller->hash; ?>">
            <?php if(!empty($controller->shortDescr)) {?>
                <div class="controller-full-name" title="<?php echo $controller->longDescr; ?>">
                    <?php echo $controller->shortDescr; ?> (<?php echo $controller->name;?>)
                </div>
            <?php } else {?>
                <div class="controller-short-name"><?php echo $controller->name; ?></div>
            <?php } ?>
            </div>
        </td>
        <td>
            
        </td>
        <td>
            
        </td>
    </tr>
    <?php } ?>
    <?php foreach($controller->_childrens as $action) {?>
    <tr>
        <td>
            
        </td>
        <td>
           
        </td>
        <td>
            <div title="Hash: <?php echo $action->hash; ?>">
            <?php if(!empty($action->shortDescr)) {?>
                <div class="action-full-name" title="<?php echo $action->longDescr; ?>">
                    <?php echo $action->shortDescr; ?> (<?php echo $action->name;?>)
                </div>
            <?php } else {?>
                <div class="action-short-name"><?php echo $action->name; ?></div>
            <?php } ?>
            </div>
            <?php if(!empty($action->Qualifier)) {?>
                <a href="<?php 
                    echo $this->broker('url')->direct(array('action'=>'edit-extend','sysmap_id'=>$action->hash));
                ?>">Add Extend</a>
            <?php }?>
        </td>
        <td>
            
        </td>
    </tr>
     <?php foreach($action->_childrens as $extension) { ?>
    <?php 
    $paramsTitle = '';
    foreach($extension->getParams() as $key=>$value)
        $paramsTitle .= "\n   ".$key.' = '.$value;
    ?>
    <tr>
        <td>
            
        </td>
        <td>
           
        </td>
        <td>
           
        </td>
        <td>
            <a title="Params: <?php echo $paramsTitle;?><?php echo "\nHash: \n".$extension->getHash(); ?>" href="<?php echo $this->broker('url')->direct(array('action'=>'edit-extend','hash'=>$extension->getHash()));?>">
                <?php echo $extension->getName()?>
            </a>
        </td>
    </tr>
    <?php } ?>    
    <?php } ?>   
    <?php } ?>
</table>