<?php echo $this->broker('headLink')->appendStylesheet('/zlyman/public/files/css/install.css'); ?>
<h2>Zly Manager</h2>
<div class="zlyman-settings-item">
    <a href="<?php echo $this->broker('url')->direct(array('action'=>'requirements'));?>">Check Zly requirements</a>
</div>

<div class="zlyman-settings-item">
    <a href="<?php echo $this->broker('url')->direct(array('action'=>'index', 'controller'=>'modules'));?>">Modules</a>
</div>