<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Eaventity_Model_Mapper_BaseEntity', 'doctrine');

/**
 * Eaventity_Model_Mapper_BaseEntity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $entity_name
 * @property integer $type_id
 * @property Eavtype_Model_Mapper_Type $Type
 * @property Doctrine_Collection $EntityValues
 * @property Doctrine_Collection $RelatedTo
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: BaseEntity.php 1224 2011-04-04 13:58:41Z deeper $
 */
class Eaventity_Model_Mapper_BaseEntity extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('eav_entities');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('entity_name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('type_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Eavtype_Model_Mapper_Type as Type', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Eaventity_Model_Mapper_Value as EntityValues', array(
             'local' => 'id',
             'foreign' => 'entity_id'));

        $this->hasMany('Eaventity_Model_Mapper_Value as RelatedTo', array(
             'local' => 'id',
             'foreign' => 'related_entity_id'));
    }
}