<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Eaventity_Model_Mapper_BaseValue', 'doctrine');

/**
 * Eaventity_Model_Mapper_BaseValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property integer $attr_id
 * @property integer $type_attr_relation_id
 * @property integer $related_entity_id
 * @property string $string_value
 * @property integer $integer_value
 * @property timestamp $timestamp_value
 * @property decimal $decimal_value
 * @property string $text_value
 * @property blob $blob_value
 * @property Eaventity_Model_Mapper_Entity $Entity
 * @property Eavattribute_Model_Mapper_Attribute $Attr
 * @property Eavtype_Model_Mapper_AttrRelation $TypeAttrRelation
 * @property Eaventity_Model_Mapper_Entity $RelatedEntity
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: BaseValue.php 1224 2011-04-04 13:58:41Z deeper $
 */
class Eaventity_Model_Mapper_BaseValue extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('eav_entity_values');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('entity_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('attr_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('type_attr_relation_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('related_entity_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('string_value', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('integer_value', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('timestamp_value', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('decimal_value', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('text_value', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('blob_value', 'blob', null, array(
             'type' => 'blob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Eaventity_Model_Mapper_Entity as Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Eavattribute_Model_Mapper_Attribute as Attr', array(
             'local' => 'attr_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Eavtype_Model_Mapper_AttrRelation as TypeAttrRelation', array(
             'local' => 'type_attr_relation_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Eaventity_Model_Mapper_Entity as RelatedEntity', array(
             'local' => 'related_entity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}