<table class="admin-table">
	<tr>
		<th width="20">ID</th>
		<th>Title</th>
		<th width="10">Actions</th>
	</tr>
	<?php foreach ($this->categories as $item) {?>
	<tr>
		<td align="center"><?php echo $item->getId(); ?></td>
		<td><?php echo $item->getTitle(); ?></td>
                <td align="center" nowrap="nowrap">
                    <a class="edit-item" href="<?php echo $this->broker('url')->direct(array('action'=>'edit-card','module'=>'pdd', 'id'=>$item->getId()));?>">
                            Edit
                    </a>&nbsp;
                    <a  class="delete-item" href="<?php echo $this->broker('url')->direct(array('action'=>'delete-card','module'=>'pdd', 'id'=>$item->getId()));?>">
                            Delete
                    </a>
		</td>
	</tr>
	<?php } ?>
</table>