<div><a href="<?php echo $this->broker('url')->direct(array('module' => 'pdd', 'action' => 'edit-card'), 'admin', true);?>">Create new card</a></div>
<div><a href="<?php echo $this->broker('url')->direct(array('module' => 'pdd', 'action' => 'cards'), 'admin', true);?>">Cards list</a></div>
<div><a href="<?php echo $this->broker('url')->direct(array('module' => 'pdd', 'action' => 'edit-category'), 'admin', true);?>">Create new category</a></div>
<div><a href="<?php echo $this->broker('url')->direct(array('module' => 'pdd', 'action' => 'categories'), 'admin', true);?>">Categories list</a></div>