<?php
/**
 * Description
 *
 * @author Serghei Ilin <criolit@gmail.com>
 * @version $Id$
 */

if (empty($this->mapper) === false) {
?>

<h1>Edit type '<?php echo $this->mapper->name;?>'</h1>

<?php
}

if(empty($this->typeBreadcrumb) === false) {
    $output = '';
    foreach($this->typeBreadcrumb as $breadcrumb)
         $output .= $breadcrumb['name'] . ' &gt; ';

    echo substr($output, 0, -6) . '<br/>';
}

echo $this->link('Edit Type',$this->url(array('action'=>'edit')));
echo '|';
echo $this->link('Rearrange attributes',$this->url(array('action'=>'move-attributes')));
echo '|';
echo $this->link('Delete attributes',$this->url(array('action'=>'delete-attributes')));