<?php
$editAction = 'edit-menu-item';

if ($this->arrayTreeItem['level'] == 0)
?>
<tr>
	<td>
		<?php
		$title  = '';
		$title .= str_repeat('&nbsp;&nbsp;', $this->arrayTreeItem['level']);

		if($this->arrayTreeItem['level'] > 0)
			$title .= '&nbsp;';

		echo $title . $this->arrayTreeItem['name'];
		?>
	</td>
	<td align="center" nowrap="nowrap">
		<?php
			echo $this->link(
				'edit',
				$this->url(array('action' => 'edit', 'module' => 'eavtype', 'id' => $this->arrayTreeItem['id'])), array('class' => 'edit-item')
			);
		?>

		&nbsp;

        <?php
			echo $this->link(
				'new_entity',
				$this->url(array('action' => 'edit', 'module' => 'eaventity', 'action'=>'edit', 'type' => $this->arrayTreeItem['id'])), array('class' => 'icon-add')
			);
		?>

		&nbsp;

		<?php
			echo $this->link(
				'delete',
				$this->url(array('action' => 'delete-menu-item', 'module' => 'eavtype', 'id' => $this->arrayTreeItem['id'])), array('class' => 'delete-item')
			);
		?>
	</td>
</tr>