Eavtype_Model_Mapper_Type:
  Type1:
    id: 1
    name: Electronics
    root_id: 1
    lft: 1
    rgt: 4
    level: 0

  Type2:
    id: 2
    name: TV
    root_id: 1
    lft: 2
    rgt: 3
    level: 1

Eavtype_Model_Mapper_AttrRelation:
  rootRelation1:
    type_id: 1
    attr_id: 1
    lft: 1
    rgt: 2
    level: 0

  rootRelation2:
    type_id: 2
    attr_id: 1
    lft: 1
    rgt: 2
    level: 0