Eavtype_Model_Mapper_Type:
  connection: doctrine
  tableName: eav_types
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(50)

Eavtype_Model_Mapper_AttrRelation:
  connection: doctrine
  tableName: eav_type_attr_relations
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: type_id
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    type_id:
      type: integer(11)
      unsigned: true
    attr_id:
      type: integer(11)
      unsigned: true
    searchable:
      type: boolean
      default: false
    required:
      type: boolean
      default: true
    inherited:
      type: boolean
      default: false
  relations:
    Type:
      local: type_id
      foreign: id
      foreignAlias: TypeAttrRelations
      class: Eavtype_Model_Mapper_Type
      onDelete: CASCADE
    Attr:
      local: attr_id
      foreign: id
      foreignAlias: TypeAttrRelations
      class: Eavattribute_Model_Mapper_Attribute
      onDelete: CASCADE