Eavattribute_Model_Mapper_Attribute:
  Attribute1:
    name: "Root attribute"
    system_name: "root_attribute" #this system name is used in some parts of system
    data_type: INTEGER
    status: HIDDEN
  Attribute2:
    name: "Name"
    system_name: "name"
    data_type: STRING
  Attribute3:
    name: "Description"
    system_name: "description"
    data_type: TEXT
  Attribute4:
    name: "Price"
    system_name: "price"
    data_type: DECIMAL
  Attribute5:
    name: "Entity"
    system_name: "entity"
    data_type: ENTITY
    status: READONLY
  Attribute6:
    name: "Resolution"
    system_name: "resolution"
    data_type: STRING
