Eavattribute_Model_Mapper_Attribute:
  connection: doctrine
  tableName: eav_attributes
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(50)
    system_name:
      type: string(50)
    data_type:
      type: enum
      values:
        - BLOB
        - DECIMAL
        - INTEGER
        - TEXT
        - TIMESTAMP
        - STRING
        - ENTITY
    status:
      type: enum
      values:
        - DEFAULT
        - READONLY
        - HIDDEN
      default: DEFAULT
  indexes:
    attr_title:
      fields: [system_name]
      type: unique