<div class="user_box">
    <?php if ($this->boxType == 'simple') {
 ?>
        <a class="user-profile" href="/user/index/profile"><?php echo $this->userIdentity->getFirstname(); ?> <?php echo $this->userIdentity->getLastname(); ?></a>&nbsp;&nbsp;&nbsp;<a class="user-logout" href="/user/index/logout">Logout</a>
<?php } elseif(!empty($this->userIdentity)) { ?>
        <div>Welcome, <b><?php echo $this->userIdentity->getFirstname(); ?> <?php echo $this->userIdentity->getLastname(); ?></b></div>
        <div>You a member of group: <b><?php echo ucfirst($this->userIdentity->getRole()->getName()); ?></b></div>
        <div class="tool-bar">
            <a class="user-profile" href="<?php
        echo $this->broker('url')->direct(array('action' => 'index', 'controller' => 'profile', 'module' => 'user'),
                null,
                true); ?>">Profile</a><br>
                <a class="user-logout" href="/user/index/logout">Logout</a><br>
                <a class="user-change-password" href="/user/profile/change-password">Change password</a>
        </div>
<?php } ?>
</div>