<h1><?php echo $this->broker('translate')->direct('pages_list');?></h1>
<table class="admin-table">
    <tr class="title">
        <td><?php echo $this->broker('translate')->direct('title');?></td>
        <td><?php echo $this->broker('translate')->direct('sysname');?></td>
        <td colspan="2">&nbsp;</td>
    </tr>
    <?php
    /** @var Mapper_Page $item */
    foreach($this->list as $k => $item):?>
    <tr class="row<?php echo ($k%2 == 1) ? '2' : '';?>">
        <td><a href="<?php echo $this->broker('url')->direct(array('module'=>'page','action'=>'edit','id'=>$item->getId()),'admin',true);?>"><?php echo $item->getTitle();?></a></td>
        <td><?php echo $item->getSysname();?></td>
        <td><a href="<?php echo $this->broker('url')->direct(array('pagename'=>$item->getSysname()),'page',true);?>"><?php echo $item->getSysname();?></a></td>
        <td>
            <a href="<?php echo $this->broker('url')->direct(array('module'=>'page','action'=>'edit','id'=>$item->getId()),'admin',true);?>">edit</a>
            <?php if($item->getBuiltIn() == false): ?> 
            <a href="<?php echo $this->broker('url')->direct(array('module'=>'page','action'=>'delete','id'=>$item->getId()),'admin',true);?>">delete</a>
            <?php endif;?>
        </td>
    </tr>
    <?php endforeach;?>
</table>