<?php
if (empty($this->page) === false):
    $this->headMeta()->appendName('keywords', $this->page->meta_keywords);
    $this->headMeta()->appendName('description', $this->page->meta_description);
    $this->headTitle($this->page->title, Zend_View_Helper_Placeholder_Container_Abstract::APPEND);
?>

<h1><?php echo $this->page->title;?></h1>
<div class="pageContent">
    <?php echo $this->page->content;?>
</div>

<?php endif; ?>