<?php
if (empty($this->page) === false):
    $this->broker('headMeta')->appendName('keywords', $this->page->getMetaKeywords());
    $this->broker('headMeta')->appendName('description', $this->page->getMetaDescription());
    $this->broker('headTitle')->direct($this->page->getTitle(), \Zend\View\Helper\Placeholder\Container\AbstractContainer::APPEND);
?>

<h1><?php echo $this->page->getTitle();?></h1>
<div class="pageContent">
    <?php echo $this->page->getContent();?>
</div>

<?php endif; ?>