<?php echo $this->broker('headLink')->appendStylesheet('/slysman/public/files/css/install.css'); ?>
<h2>Application Modules </h2>
<table border="1" cellspacing="0" cellpadding="3">
    <tr>
        <th></th>
        <th>Module Name</th>
        <th>Module Description</th>
        <th>Enabled</th>
        <th>Actions</th>
    </tr>
    <?php foreach($this->modules as $moduleName=>$bootstrap) {    
        $moduleOptions = $bootstrap->getOptions();

        ?>
        <tr>
            <td><input type="checkbox" name="modules[]" value="<?php echo $moduleName; ?>"></td>
            <td><?php if($bootstrap->hasOption('name')) echo $moduleOptions['name']; else echo ucfirst($moduleName)?></td>
            <td>
                <div><?php if($bootstrap->hasOption('description')) echo $moduleOptions['description'];?></div>
                
                <?php if(!empty($bootstrap->moduleRequirements['modules'])) { echo '<div class="slysman-requires-label modules">Require modules:</div>';?>
                    <ul class="slysman-requirements-modules">
                    <?php foreach($bootstrap->moduleRequirements['modules'] as $name=>$version) {?>
                        <li><?php echo ucfirst($name).' ver.'.$version; ?></li>
                    <?php } ?> 
                    </ul>
                <?php } ?>  
                
                <?php if(!empty($bootstrap->moduleRequirements['resources'])) { echo '<div class="slysman-requires-label resources">Require resources:</div>';?>
                    <ul class="slysman-requirements-resources">
                        <?php foreach($bootstrap->moduleRequirements['resources'] as $name=>$version) {?>
                        <li><?php echo ucfirst($name).' ver.'.$version; ?></li>
                        <?php } ?> 
                    </ul>
                <?php } ?>  
            </td>

            <td align="center">
                <?php if($bootstrap instanceof \Slys\Application\Module\Enableable) { ?>
                    <?php if($bootstrap->hasOption('enabled') && (boolean)$bootstrap->getOption('enabled') == true) echo 'enabled'; else echo 'disabled  ';?>
                <?php } ?>  
            </td>
            <td>                
                
            <?php if($bootstrap instanceof \Slys\Application\Module\Installable) {                    
                if(!$bootstrap->hasOption('installed') || (boolean)$bootstrap->getOption('installed') == false) { ?>
                    <a href="<?php echo $this->broker('url')->direct(array('action'=>'proceed','deed'=>'install','item'=>$moduleName));?>">Install</a>
                <?php } elseif($bootstrap->hasOption('installed') && (boolean)$bootstrap->getOption('installed') == true) { ?>
                    <a href="<?php echo $this->broker('url')->direct(array('action'=>'proceed','deed'=>'uninstall','item'=>$moduleName));?>">Uninstall</a>
                <?php  } }?>

            <?php if($bootstrap instanceof \Slys\Application\Module\Updateable 
                    && ($bootstrap instanceof \Slys\Application\Module\Installable && (boolean)$bootstrap->getOption('installed') == true)) { ?>
                <a href="<?php echo $this->broker('url')->direct(array('action'=>'proceed','deed'=>'update','item'=>$moduleName));?>">Update</a>
            <?php }?>

            <?php if($bootstrap instanceof \Slys\Application\Module\Enableable 
                    && ($bootstrap instanceof \Slys\Application\Module\Installable && (boolean)$bootstrap->getOption('installed') == true)) { ?>
                <?php if($bootstrap->hasOption('enabled') && (boolean)$bootstrap->getOption('enabled') == true) { ?>    
                    <a href="<?php echo $this->broker('url')->direct(array('action'=>'proceed','deed'=>'disable','item'=>$moduleName));?>">Disable</a> 
                <?php } else { ?>
                    <a href="<?php echo $this->broker('url')->direct(array('action'=>'proceed','deed'=>'enable','item'=>$moduleName));?>">Enable</a> 
                <?php } ?>    
            <?php } ?>  
                        
            </td>
        </tr>

        <?php
        }
    ?>
</table>