<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Eavattribute_Model_Mapper_BaseAttribute', 'doctrine');

/**
 * Eavattribute_Model_Mapper_BaseAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $system_name
 * @property enum $data_type
 * @property enum $status
 * @property Doctrine_Collection $TypeAttrRelations
 * @property Doctrine_Collection $Values
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: BaseAttribute.php 1249 2011-04-28 15:02:58Z deeper $
 */
class Eavattribute_Model_Mapper_BaseAttribute extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->
        $this->setTableName('eav_attributes');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('system_name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('data_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'BLOB',
              1 => 'DECIMAL',
              2 => 'INTEGER',
              3 => 'TEXT',
              4 => 'TIMESTAMP',
              5 => 'STRING',
              6 => 'ENTITY',
             ),
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'DEFAULT',
              1 => 'READONLY',
              2 => 'HIDDEN',
             ),
             'default' => 'DEFAULT',
             ));


        $this->index('attr_title', array(
             'fields' => 
             array(
              0 => 'system_name',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Eavtype_Model_Mapper_AttrRelation as TypeAttrRelations', array(
             'local' => 'id',
             'foreign' => 'attr_id'));

        $this->hasMany('Eaventity_Model_Mapper_Value as Values', array(
             'local' => 'id',
             'foreign' => 'attr_id'));
    }
}
