<table class="admin-table">
	<tr>
		<th width="20">ID</th>
		<th>Name</th>
		<th>First name</th>
		<th>Last name</th>
		<th width="50">Role</th>
		<th width="20">Active</th>
		<th width="10">Actions</th>
	</tr>
	<?php foreach ($this->pager as $item) {?>
	<tr>
		<td align="center"><?php echo $item->getId(); ?></td>
		<td><?php echo $item->getLogin(); ?></td>
		<td><?php echo $item->getFirstname(); ?></td>
		<td><?php echo $item->getLastname(); ?></td>
		<td><?php echo $item->getRole()->getName(); ?></td>
                <td align="center">
                    <a href="<?php echo $this->broker('url')->direct(array('action' => 'publish-theme', 'module' => 'templater', 'id' => $item->getId()), 'admin', true); ?>" class="icon16 <?php
                    if ($item->getActive())
                        echo 'icon-published'; else
                        echo 'icon-not-published' ?>">
                    </a>
                </td>
                <td align="center" nowrap="nowrap">
                    <a class="edit-item" href="<?php echo $this->broker('url')->direct(array('action'=>'edit-user','module'=>'user', 'id'=>$item->getId()));?>">
                            Edit
                    </a>&nbsp;
                    <a  class="delete-item" href="<?php echo $this->broker('url')->direct(array('action'=>'delete-user','module'=>'user', 'id'=>$item->getId()));?>">
                            Delete
                    </a>
		</td>
	</tr>
	<?php } ?>
</table>