<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Eavtype_Model_Mapper_BaseType', 'doctrine');

/**
 * Eavtype_Model_Mapper_BaseType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $TypeAttrRelations
 * @property Doctrine_Collection $Entities
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: BaseType.php 1224 2011-04-04 13:58:41Z deeper $
 */
class Eavtype_Model_Mapper_BaseType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('eav_types');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Eavtype_Model_Mapper_AttrRelation as TypeAttrRelations', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('Eaventity_Model_Mapper_Entity as Entities', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($nestedset0);
    }
}