<?php echo $this->broker('headLink')->appendStylesheet('/slysman/public/files/css/install.css'); ?>
<h2>SlyS Manager</h2>
<div class="slysman-settings-item">
    <a href="<?php echo $this->broker('url')->direct(array('action'=>'requirements'));?>">Check SlyS requirements</a>
</div>

<div class="slysman-settings-item">
    <a href="<?php echo $this->broker('url')->direct(array('action'=>'index', 'controller'=>'modules'));?>">Modules</a>
</div>